spring.application.name=PLUSHOME

#Server 
server.port=8080
server.servlet.context-path=/api

# Oracle DataSource
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=plushome
spring.datasource.password=a123

#MyBatis
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
mybatis.type-aliases-package=com.spring.home.dto
mybatis.configuration.map-underscore-to-camel-case=true

#Logging
logging.level.com.spring.home.mapper=DEBUG

#Profile: secret 파일 함께 읽기
spring.profiles.include=secret

#File
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

#security
spring.jwt.secret=snskrkskfmfghkskrpaksemfdjttmqslekdkdhwlswk

#openai
openai.api.key=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